import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import SessionWrapper from "@/components/SessionWrapper";
import RemoveHash from "./removeHash";

export const metadata = {
  title: "Get me A Chai",
  description: "Generated by Get me A Chai - Fund your project with Chai",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#000000]  bg-[radial-gradient(#ffffff33_1px,#00091d_1px)] bg-[size:20px_20px] text-white">
        <SessionWrapper>
          <Navbar />
          <div className="min-h-fit md:min-h-[84.5vh] ">
            <RemoveHash />
            {children}
          </div>
          <Footer />
        </SessionWrapper>
      </body>
    </html>
  );
}