import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import SessionWrapper from "@/components/SessionWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Get me A Chai",
  description: "Generated by Get me A Chai - Fund your project with Chai",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SessionWrapper>
          <Navbar />
          <div className=" top-0 z-[-999] min-h-[85.6vh] h-screen w-full bg-[#000000] bg-[radial-gradient(#0f172c_2px,#00091d_1px)] bg-[size:20px_20px] text-white"></div>
          {children}
          <Footer />
          
        </SessionWrapper>
      </body>
    </html>
  );
}
